//NO RED 2s
const deck = 
[
    //spades
    {
       suit:"spade",
       value:"two" 
    },
    {
        suit:"spade",
        value:"three" 
     },
     {
        suit:"spade",
        value:"four" 
     },
     {
        suit:"spade",
        value:"five" 
     },
     {
        suit:"spade",
        value:"six" 
     },
     {
         suit:"spade",
         value:"seven" 
      },
      {
         suit:"spade",
         value:"eight" 
      },
      {
         suit:"spade",
         value:"nine" 
      },
      {
        suit:"spade",
        value:"ten" 
     },
     {
         suit:"spade",
         value:"jack" 
      },
      {
         suit:"spade",
         value:"queen" 
      },
      {
         suit:"spade",
         value:"king" 
      },
      {
        suit:"spade",
        value:"ace" 
     },
     //hearts
     {
        suit:"heart",
        value:"three" 
     },
     {
         suit:"heart",
         value:"four" 
      },
      {
         suit:"heart",
         value:"five" 
      },
      {
         suit:"heart",
         value:"six" 
      },
      {
         suit:"heart",
         value:"seven" 
      },
      {
          suit:"heart",
          value:"eight" 
       },
       {
          suit:"heart",
          value:"nine" 
       },
       {
          suit:"heart",
          value:"ten" 
       },{
         suit:"jack",
         value:"jack" 
      },
      {
          suit:"heart",
          value:"queen" 
       },
       {
          suit:"heart",
          value:"king" 
       },
       {
        suit:"heart",
        value:"ace" 
     },
       //diamonds
       {
        suit:"diamond",
        value:"three" 
     },
     {
         suit:"diamond",
         value:"four" 
      },
      {
         suit:"diamond",
         value:"five" 
      },
      {
         suit:"diamond",
         value:"six" 
      },
      {
         suit:"diamond",
         value:"seven" 
      },
      {
          suit:"diamond",
          value:"eight" 
       },
       {
          suit:"diamond",
          value:"nine" 
       },
       {
          suit:"diamond",
          value:"ten" 
       },{
         suit:"diamond",
         value:"jack" 
      },
      {
          suit:"diamond",
          value:"queen" 
       },
       {
          suit:"diamond",
          value:"king" 
       },
       {
        suit:"diamond",
        value:"ace" 
     },
       //club
       {
        suit:"club",
        value:"two" 
     },
     {
         suit:"club",
         value:"three" 
      },
      {
         suit:"club",
         value:"four" 
      },
      {
         suit:"club",
         value:"five" 
      },
      {
         suit:"club",
         value:"six" 
      },
      {
          suit:"club",
          value:"seven" 
       },
       {
          suit:"club",
          value:"eight" 
       },
       {
          suit:"club",
          value:"nine" 
       },
       {
         suit:"club",
         value:"ten" 
      },
      {
          suit:"club",
          value:"jack" 
       },
       {
          suit:"club",
          value:"queen" 
       },
       {
          suit:"club",
          value:"king" 
       },
       {
         suit:"club",
         value:"ace" 
      },
      {
        suit:"joker",
        value:"small" 
     },
     {
        suit:"joker",
        value:"big" 
     }
];

export default deck;